# /etc/pulse/daemon.conf
daemonize = no
high-priority = yes
realtime-scheduling = yes
realtime-priority = 5
flat-volumes = no
exit-idle-time = -1

default-sample-format = s16le
default-sample-rate = 48000
alternate-sample-rate = 44100
avoid-resampling = yes
resample-method = trivial

default-fragments = 4
default-fragment-size-msec = 10

enable-shm = no
lock-memory = no
scache-idle-time = 0
shm-size-bytes = 524288     ; 256 KiB pool (reduce further to 131072 if needed)

; Optional caps to keep PA small
rlimit-as = 134217728
rlimit-data = 67108864
